### ISSUE TITLE
seems like [] while concatting will read the empty array like an [undefined] array

### ISSUE THREAD

**Issue by elgubenis** [bigShai/extendify#4]
hi, im using extendify to extend an object which has an empty array in one of its keys:
```js
data = {
  items: []
};
```
with another object which has items in the items array:
```js
data = {
  items: ['test']
};
```

which i though would result in
```js
data = {
  items: ['test']
};
```
while having arrays: 'concat' in the options, but i get this:

```js
data = {
  items: [undefined, 'test']
};
```'

where should i go and look to fix that? or is that alright like it is?

**Comment by bigShai** [comment]
Hi Linus,

Thanks for your email.
I don't have the time to fix/research this issue at the moment, but if you
want to fork and fix, I'll be happy to review and upload your code.

**Comment by lazabogdan** [comment]
+1

**Comment by Rendez** [comment]
+1

**Comment by elgubenis** [comment]
thanks!
